theme: jekyll-theme-minimal
logo: assets/PeterKugel.jpeg
title: "Peter Kugel"
description: "Retired Computer Science Professor Peter Kugel passed on October 11,
2021 at the age of 91 after a long and happy life."
baseurl: "" 


